apiVersion: v1
kind: Service
metadata:
  name: database  # Nombre del servicio (usado en la URL de conexión)
spec:
  type: ClusterIP  # Servicio interno
  selector:
    app: database
  ports:
    - port: 5432
      targetPort: 5432